# ==============================================================
#  ShowAlert.ps1  –  SELF-CONTAINED, no extra files needed
# ==============================================================
#
#  HOW TO CUSTOMISE
#  ----------------
#  1. Get Base64 of YOUR image (JPG/PNG/BMP):
#       [Convert]::ToBase64String([IO.File]::ReadAllBytes("C:\path\to\image.jpg"))
#     Copy the output and paste it as the value of $IMAGE_B64 below.
#
#  2. Get Base64 of YOUR sound (WAV):
#       [Convert]::ToBase64String([IO.File]::ReadAllBytes("C:\path\to\sound.wav"))
#     Copy the output and paste it as the value of $SOUND_B64 below.
#
#  3. Run:
#       powershell -ExecutionPolicy Bypass -File ShowAlert.ps1
#
#  Currently uses a placeholder red-square image and silent WAV.
# ==============================================================

# ── SETTINGS ──────────────────────────────────────────────────
$DelaySeconds   = 30   # seconds to wait before showing
$DisplaySeconds = 10   # seconds to show image/play sound
$ImageExt       = "bmp" # extension that matches your embedded image (jpg/png/bmp)
$SoundExt       = "wav" # extension that matches your embedded sound (wav/mp3/m4a etc)

# ── EMBEDDED IMAGE (Base64) ────────────────────────────────────
$IMAGE_B64 = '/9j/4AAQSkZJRgABAQAASABIAAD/4ShxRXhpZgAATU0AKgAAAAgABgESAAMAAAABAAEAAAEaAAUAAAABAAAAVgEbAAUAAAABAAAAXgEoAAMAAAABAAIAAAITAAMAAAABAAEAAIdpAAQAAAABAAAAZgAAAMAAAABIAAAAAQAAAEgAAAABAAeQAAAHAAAABDAyMjGRAQAHAAAABAECAwCgAAAHAAAABDAxMDCgAQADAAAAAQABAACgAgAEAAAAAQAABJKgAwAEAAAAAQAAA1SkBgADAAAAAQAAAAAAAAAAAAYBAwADAAAAAQAGAAABGgAFAAAAAQAAAQ4BGwAFAAAAAQAAARYBKAADAAAAAQACAAACAQAEAAAAAQAAAR4CAgAEAAAAAQAAJ0kAAAAAAAAASAAAAAEAAABIAAAAAf/Y/9sAhAABAQEBAQECAQECAwICAgMEAwMDAwQFBAQEBAQFBgUFBQUFBQYGBgYGBgYGBwcHBwcHCAgICAgJCQkJCQkJCQkJAQEBAQICAgQCAgQJBgUGCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQn/3QAEAAr/wAARCAB1AKADASIAAhEBAxEB/8QBogAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoLEAACAQMDAgQDBQUEBAAAAX0BAgMABBEFEiExQQYTUWEHInEUMoGRoQgjQrHBFVLR8CQzYnKCCQoWFxgZGiUmJygpKjQ1Njc4OTpDREVGR0hJSlNUVVZXWFlaY2RlZmdoaWpzdHV2d3h5eoOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4eLj5OXm5+jp6vHy8/T19vf4+foBAAMBAQEBAQEBAQEAAAAAAAABAgMEBQYHCAkKCxEAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwD8kB8J/gcZDjwhogHp9hgx/wCgVcj+EfwRx/yJuiH/ALcYP/iKx49afd7Voxa3M0m7JxivA95aM3dOytE00+D/AMCWT5vBuig+1jB/8RSj4NfAwnC+DtFwP+nGD/4inQazGO/51s2uuW7NiueqpNaOw6VHVJ2sYp+C/wAEj9zwfoij/rxt/wD4ikHwU+CCnP8AwiOin/txt/8A4iuqGrW+KiGsxDjH6VzRhVW0j0lQTVkZC/Bf4D+Xg+DtFH/bhB/8RVC4+DPwPB2R+D9F/wDAGD/4it6XV5CPkxVFtUvWG3cB+FdCjJ7sv6ulG76HE3fwh+DIn8qDwhoxb/rygH8krnbz4PfCtnAi8IaMP+3KH/4mvrvwT8Jb/XIU1XViY43G5VHUj3r6D0n4ZaHaRLHDbqfQlc1+38K+COYY3DrEVpciey6/8A/krxB+lbk+U4t4HBU/auOjd7L5aan5C6j8LPhfaXHz+FNJUH0tIv8A4mq1z8JvhJqEOIPDWmIy+lrEP/Za/XzxD+z54Q8Y2D213AYJf4JogFZT/Ij2Nfnl8Svhhr/wq8SLpenHfFLzDOowrqPbsR3FfN8ZeH2Oyh+0nrDuv1Pu/Cvxvynid+wh7lb+V9fTufP9r8KvhlazYn8MaWV/69Iv/ia9M0P4QfCK+gMzeFNJPljPNlD/APEVs2unHUZFikbOTxjtX0rZ6H4Q+G3gZ/FnjBJbwArHBZwf6y5mf5YolxzuduAPx6CvhFX1P2WVJpX6HyVbfCL4Z+ONVbTNP8J6PaWVswWWSOxgVmP91SE/P0r9KPhJ+yB+zz8QfhzP4Vi8D6AL+SCWCOf+z7fzAWUhW37N2Qcc5r2T4c/8E5/jL/wy7e/tBa8Eh1aRzqJ0aCPCx2R5ZYf4iYRzzkvhj6CuV+BHjiXwP4vtLqds/ZmAb0r2sDilL93R2OSmpxVmfFH7Gf7Lf7N/ib4s6Z4Q+Pfh+ysNFtdet0XW1tIBLbecdkUuXQhVE6qjPj5VYmv7Qf2Wv2Lf2CPDmsD9mz4z/AAP+H2razbQi90fVpvDumsdVsv4GL+RhpVHDepB9s/hH+1B8B9L8CfEO3/ah8J2wvPB/jNFs/EVrGOIbiQBVm46CUdCOkg/2hX6U/sj/FPV/jH4Zh/Zk8VakI/H3g6Iar4G1tztN/ZqMrAz92AXaw7bc4/d8/Utxr01JHnxquErH7WJ/wAEyv8AgnIv/NBPh7/4Temf/GKk/wCHZv8AwTk/6IJ8Pf8Awm9M/wDjFei/sufH63+O/gM3Opx/Y/EWkP8AZNXsmG14Z0+Unb2DFT9CCO1fTNeSe/SacbxP/9D8Qri5eCMyp81UY/F13GAFiXA+taeiWf8AaNuLZAdw6cUy78C6kjboxxXiVlqbQvuQJ94dxWrbXWaflSqZ09nbWuCBitGC2tnXcRxXEf2e6nBNaFnLLbfLQbxeqMmG1jFxJZy/cuOf1r1i+m/0RI14K4q6/h7Q/E+hpcBB9oa3IYDjBxVSLS5LXwhYybSVXdgf7tdnM7WPrMPFRg2i38E7qXSfH/hm9tWMc0V0oDDqOaP2pLWS5tfEF7OAfPvLuVj6kuO9cB8MbjTdO8b6VNqrHy1m3LhM/MB8vf1r3H46eMvCY8CatFBMks94yoUXJBHl5PanPdk4S/PY/qL/AGZPE9x4n+CPhC/upDJMtjHE7HqdgAr6PBJGQa/N/wDYe8UX2pfAzRNPnmaRLVWjQMc8Bj/hX6PRnNcL2PlpLUkoqOirJJKKKKACiiigAooooAkooooOgKKKKACiiigAooooAKKKKACiiigD/0fm8N+/m/wCuhpN3P51XEg+0Tf8AXQ0wydcHsa8sLEm/PenA5NUg1TK3PJpoEWcn1p+D61BTwasOUkwfWozuPelpu2gOUfk0ZNJRQAuTRk0lFAEuTRk1FRQBLk0oJzUNFAFwE4pc881WpwPY1maqRaytODYqrRSsa86J/Mo8yquTRk1HKYcxZ3560bxVbJoyaXswuThhS7xUVFZOmbRmWKDzTM4p26syaNUJMZRSgHrRgVKNopDaKXFGKs2QlFLijFWtgYlFOxRii5PKxKKXFJiiyC0gooosGglFLikosMSjFLjmikAYoxSimAUoVjyBmlGTwK7LwrpH2s/apV+Qfd9660jAn0nSWVfOlGK6iO3DHihtiFETHIqws3pWsWZiT2oSPJGakjj7VcCqex5qwqbqQGaIVzjFI9qOw7VsiPFRuu0elAGJJaHsKi+zSDtXR+TuGSKTyqCbmCLaXPSrMdnKw5FbYj5pCAKCWzKSxBJ3DitGO1jUVGZwO9Rm+VTgmqFcuNHGKjJFJHKk46/pWb9tGcZoA2MYpN2KpJcqRnNWlkVhxQIf5vpR5vtQLge1KLge1AHiHxXtXPhO7IP/LtJ/6Ca/JO9mNvJJGeQOlfr18aL1T4Su1zndbSj/x01+QOo3e3UblBxg9K9zC76HlY3ZM9U8L6y6NGSc8ivrrwReZjTP8AKvzS8P6sbecAt0r7B8E62JljBb0r0I7GR7Be6B/aVtPGQMlT/KqPw88dw/DHWJPCvijMdm27ypCeA3rXXWFys1q8TcnFeN+OLf5NwHKk81gdBJfWfxT8Ya5B4i8E3GZLJtkqxqTkZ618mfGLw/8AE/XtcM2taa0bqclIWKKB9K+sPgVqNxb+f5eSuRiu18daolrCshXe7cgnpQFzM/Yd8ReN9Y03VbHxwCrWbhbR5OsjrnaM+lfeUMSW0KwQjCIMAV8b/AqWTWYp9StBsjdmUY9K+mJJHdFD8sBk0W0MsQ+6v0oA2zqnlRg5+YcGs28vvtB2huK5e6vmSTanUVXW7k3bh1oA6q2kkPJJqpJJiQisTT7uWVtrnitvCsuPWgCuBzWikWAKqw25kB3Vo7QO9AEdFRm6gVim/nFRtqFsvWQUAX6Kz11KzbowoGpWp/5aLQBoUUmRQaAOooooOgKKKKACiiigAooooAKKKKACiiigD//S+LJT+8Yf7RpT2pDGS5PrS4wOleSzoCikxS1LbAKKKKQBRRRQA7bUsbBW5qOpEGTisq9kcmIqcqOzs7vzNoPStrz1BxXH2kpjINaUt0SeK8WpUlc+JxGIalaxs3NwO1c9cXCrnJqhqGpFQVzWRBevOSGJrh9rcxp16j6mjJdj1qjNdNGMbqpyXLE/e4NNiUz8g5qqVNvqbSmkrollusg88VVijkuJRDCMs3SpYrKaVtqCtq3tIbFNw5c9aNvlX5R+P5VtGFup0qlGEbs6DTtNjsFyx3N3rdjt2kHyg1mWtxC8KiVcN6VqQ3mOMYFbxb6M76FbWx5545eKO4Fru4j7VieF4bR5TJcgEA11fjbw3L4k0gw2jAXCHco9cfSvFdB8TvpWoHR9bHkyxcKXHBHavExOIcJNI+wy/CRqxjKx6bq6w3VvJCVJDqR+deJz+HzAzQNne3PNe4vbpqECXUf3GUMK4jxDb/ZXKIPlf9BXJzH0VPEypKyJPgDoEth4y0bVXX93FdqGJ7Zr9LYzgcV+fnwZvPsWreHpj02jntzX6BxHMYoqaTvdG8ZXRYXpSgkmigHjBqztL0FrSijkUwF5oHCkikz7UtABgmlXvzSA9qVDzg0AdVoiksNpFe8+E9H86NJXGMDmvBNHYFhnJXPNe/8AhK4CwKd2MiuGvse1lo0VpdBHnBjOO3Wpfhrqtrb3k/h+7O23nJCH/aHIr1JbGB0OFBzXit5FJZ6sJ0A3I3T2rilTS3OaVPmu0epTfBnXdLt7a7iJEMuGjPvVf4b/ABa8Q/Di51HRNWi+1PbJsMR7D8B/9evobwPq51Pw1YXgGeEx+Fecftsaf9k0v4b64uMj7VasfqQy/wArJ/SvX4Yd3GVzws5i6ba7Hpnw3+Keh/EPSPtNkcKP4SK7mLDjC9K/KH4EapcaBe3+kI5WCRw6oD/DX3L4V8SrdKiHrX3ihynykJ6nphJpKrRzAr0q2DmsrnSKvSkUE9KcetSKMZ4oAjVMH0rO1oqNKvOB/qJP/QTW4OlYPiWMHQtRB/59pf/AEA0AflroN1suIjjO01+h/gXWxNYxHPavy60K4MUqhWx8x/nX3t8Dbn7XpFuWbJ20HoYWq2e9n5ec9DXK6/YtNH5i9VFdSFJH1NcV4m1P7LA4P8ACpFdFNe8cFSSSOWgaWxkW4i9c5r0C2uRdRLKvXGDXlUt5I6hgTzXS6FqTM3kNzzXZY8yUramz4jtopbaWKVQQQetc34EH2GeW3HSBsj8a9DuIhdxqnoK8s06eXT7u5Ac4zxWLQ4s9d8S+E/FGsa7FqVlpslzAV27YxuIPfivubwHcJN4Pt4ycNDujP4GvmD4Ba7ZXVhbGeQfatwKk9vwr6b8IaRFp2liYHdJKxZj65NTJWdyU9D5t/bbuIrPVPhfezNhFvgPx3yf/Yr6q/al1CSHS/CVxEwV21CA5P+6a8G/bP0pNZg8A7V3Pb3bqT2GZiP6193fE/wLYfE/wCCenWl46i6sbWK8tJCP9XInIGffpULRmz3PE9C8U6g0FvDcOH3xqxYDHJGa9a8A6pqM+q4nvCT/q8Pt/9CzXi3wO8WTeINZvtJd/Nmsl3buxA45r0Hwm6t4k1R1OGiJjHt61lONkS/iPoW/sGfC3Mig54J5NcmNGa4mEkzbUHatqfWRHBJIflCKSce1cv/aatH5koK+YRt9utJbHRFW2MHXrHT9W1ONpFJliGA3YVlaj8NdG1/SbqC4t1E00TI3Pv7V11ho/2m53XnESevsKbPeR21yljE2HkJB9sClFM0ckjH+Cvh7RNB+FWgQx28aMbZTnHPJIrYn0iyfnYBXknwO8c3UvhXTtH0eHYtspEjEdSCRXqljr2o3sTtMu0qcHPXiuZ0tbnQ5abE1jTbKKVjGmSa5HWoZFb5cKR3FdT/a0UilWGCRgg96xL63W4tpVwTtOfoRTitCVJI800K7mh1OdG53OSfpXpFrOrrnFea2mReSr0r1CzZJI9q1Y+RmBqmmtM5AFeTeI9B+1LI7Kc/h1r2RiWiHWuLvEXDeWMHJrkqK7M6is7HzXe6BqixOGUjHqK5240+8tvlyT7V9FXXhsahA06Dkg159P4UvEuSpjIU9eK82pJ7H1GBhFxbPHGivVTLnH41kSPOv3l59q+gPEXw91OzhFnChc4BJIBH5Vy48Ia1K3kiAAjoSePy9a551Ldz08PFXbOHht2nO9RwO9acds2M/wA6rXFvcW8bRSpsYcYq1btIFGcD3rJzO2VO7Qkbsp5PBqytpHKetSXFrEyDIHSqH29bZwicH3rppybWpxVEkTQ6ZFn5utJLpSbcCqR1YrJlSSaybjXEjfczfnW/MtGceJqKK0LU2jyRklWyKoSRnGGHI61ix+IVfgNyKlTW0DfMeDQnqcP1ipfQ14owg4pzEdBSw3sMo2q1SHymTJPWt41UlseXi3Ka0KO3Peql5FmM1pFU7mqN1CGB29K7aNVStY8GfxM43y3WcEf3q6XTbkdWNcrPcNDKyHpV6zu2iUHOa64OxlH3T1/S7rHr1r1Gx1oQRD5q8E0K9+0OuTXYSzELx3r5vNaLdj9F4arJaM7jxL4q0TVreW3juV3Hpu4xXiep+IFbULgWs0TxKxCMrA5FdPqAaGAO2M4PvXi+kRJc6pqEzH7rfyr4Xn5rs/WKFGE4HqH27epBNR/bpB/8ArVyCaqlrLGkTZJ6jNdHc3cEtsJCRuHUUuYqUF2K7atIV2s3FSjVpRwXNYsqJdkyIOnTFPt4j5YUmqc7IhUkbnk/1qxGxHPHrWbLcSKzE81WkuDjGc1p7M1ULGkLiWNcqfzqJ765B5Y+9LakXA5bBqQ2nYGuirFpGlKJ7d4K/4J3/AB8+JPhgeLtB0pFsHUskkkg3OBwdoGc4Pgfxj+DfiP4HfEG58CeJJVe5t/3oI5VlY8HnjpX9JFzLoeleAdNtVhWKJLVNioRwAOoHFfy/ftKePJviv8btd8UrfyXOlNMlrYtKxYLbwfKhH++cn8a+j4dwtCcpJq7R+e8a5jiMNTpq/uvdH19+wZq1v4i8H3lleuMxOuyn/aA/n0r9GNEk8m2WBTuLcKa/FX9h74tXPg3xZf8Ah25Yz2UkpIz1Hoa/W2w1K0udNimmcK23Oe9fRZhlfsWfH5Zmnt6cXLdHo0VpKqIsvG4A1aEGFJArHi1+ydNpdfXJAoTXrXLBWUgCvGvud3tLnlX7Rf7PGnftJfDC78FXjJDdA+baTMOElUfKc/iRXg/7GWqeOPhj8U7L4R+MpgBp8f8AaFix6PHFxk/7yt+VfYZ1W2mUjcpB96+RfjvqsHwS+O/wr8XJGkmiWGrvbXkhGYoFnJCswHqp9favEzfCqEXJbMipRTPS/jD8ZfGvhqz8W/DY2J1FRqN7ai+iYb7SXTijbfMz1MkPCnt0/GvpL4ffthfCzxlBClzexw3TAMT1wR1r3r4neKvhle6J4b8Q/D7ULaYajH5U2x0PlMrEFQCBnPr0rxd/gN8Pbi5a1OmxXUEoJimK42Nzj5e2K+O5a1Kpyyi0j6SnQpTipKSbPqrwr+1XqOtPb2t3oaxFiAx9DX0roWvPeIssnAAr8pB4GsdFvWh0lXtJUHCoflP0r7J+Cfji10PQTYaswSUA7c/xp/MVVHMpwly1UjopZfH7LPunUJYLyCNXA4UGvmrx18PPBF5qL6h4h02CW6iJ/ekfN+Yr0pvGWm3NvvtWzkV5Z4k1bSdRvprJpQbjB3ED86+vybMKkne54ublKjFxjJrTzPz88c+GtBt9U1PwraWWnalezJM6tG4QEA8c5rx+3+A8Vkc23h3Rhv67SzflX2xq/w48LXni2bxHqls73ZBjQFzxk88Z7133gjwTaXMiS39ms10f9XG3C5r7PC4ytQ1i7n5vmFOnic0jGeiS09Dj/h18LJtNtk1iBILbzVGFUqf0rY1r4e6jY6lbTa7ZRvBuC/IEKnP0r6Z07whHp8Iu7RFLqMgg4x+NUI9Bur3WVlvNzRwnhCMrk96qeZ1Yys9T6HB8NpLmWqOw8IyW0+jwGBVGR0C4xXSWk2I+BXOfY47RYoYxgDGa3re5VVFZy1d2exBOyOvtLsBeWrXSTO0V43pd5m7C5r1mC7RExyar7HXJamfqLhkO6vPL1B5pBHWusv75FHBIP1rgL67V2kIPX19aASKWsxYhKGs7TNXFpCISa5HU7mWXnmuQ13xCNKtGLk5b7opN2QW1Ox8c+Jf3flRtXmOnxPNcF24NZuoeJpL5gNxxVuwmH2cSHqaxbuyGelR2JMKtnpXHajFg4rqk1gS2wAP3azfJW4O49KqLuJxseW6hasg3HtWJBLJJPmM8HmvRNc0WO5jwB+Fcg2kyROWXIxXVSqGbQ7TrqWCYSKc4NUDPE8rR9iasCKaAbBmu0jiWS2WXHXtUS3NKc3fQ9q8LXy3FqiknOOK+oPAk4+RCa+S/Cs7LMgBr6g8BXgEavnqB1r4fN6bU7n6Rw/ONRWPaNJl4XFa6yetcxpUxWNfTIrordya8OlJvQ+uxVFRSZshxjmmllHBNVoHJFSPwMnnNdEXc8aUkmUZV+Y5oWL1oaQsePSplBK5FaSmZqCFjtV9KBaKe1Tj5TT1BIqOYHToQ/ZQT0pi26BufSrkSGTqCRVlbfb1rGTOqEEYrQovYVla0s9F4uFLdq6KSPnisq8tgwz1rkxFOL6HZS1PML63huFaFkDkdK8r1fw5Y28u5FAbsQK9fvLRUkKN1FcFeQLuYr1r5vEUIqLufe5LiZXaZ5RD4VuVl37cgjpW+1kYYkRBk11JiLxFR0Nc7NiJsV8tXpuEj9SyjF+0hZszJLRpQO2KtWNiYWz2p9vPGdwzST3g3cE14U4u97n6PhJNKzNC7urnT52glHy4yDnIrjb74j+FLG6e0ur4LL0I2tyPQ1BJ4ikLYJ5HpXNXHhHwdqU5vbu0E84wNx71507yW5+hYJJQsmb7fFHwEFxHrVqhHof/rU3/hZ/gEcrr9mPwr//AFNPGSQeMRjkKOM9BXiXxN/Z38A3bIz6bNaqpGFgkZVH5E0pQbXNFHpVHGKvKx9peFfF/h3XkX+ytRS4B7rn+ldqjZOQa/BDUNL0n4eeJpfC9jqt3HC7ZjR5mcRr2614/wCNvizqfhvUhFBqhgPo1e3kU6sqkqVRbnz3FcKUIRrUXpc/pl1Lx/4a06LzLy/jjX/a4rxK4+PGiRa1c6VFPHI0GcMG65r8JP8Ahffj67BN1q8koI67ia5ab4p+M9Rla4uNTl3ydDv9a+rp0Jw36HwSxGHlqkfsN8UPHGnavp97p8U6O0gbHNfCM26SQOP4eTWfo1pd6+FnmZ/MPUmp5dNlt3Kt2rqSJbNbz8U37QQaYbcmpGtJEHzYxUtFxlZmiPiHqCOyKx4PoKuReI9YYbiCRXCXQFvLsaq0VzIjbQ3FQ4uxSlc9oa51K4Uc4rrPBeqa3DEY/IaWP+8BXlvhVWcBia9j8FuFIjfv1rKasMzdQ0bxV4jvHDWYgDd2bArqLf4daro1sl7rU0MckmMMpyDxzXpttcQOowR9a8k8TeIhcapJBk4VsAV49bGKi7bntYXB1MRF2Whu3j3FmOWDj1qJr+Y9d2PSud+32k0gS9OBW1DeWjQ7oSWQ/3jXLHHRkrpnfPLJJXRqG6nVc7j+FW7Bri5Vyw6VkJfQK3zSe/Na9hqNjvdEKlH6HNddCupTtY8/EYOcI3Z1trJcxJkHipG1G7IHzEVlLfxJIVSXbn0zViKWa5OHbp2r0qlH3DzKdRxkblhfSq/zfyrfik8xQRXCLJKsgCtwK6Syu9kYVzXj16Lj5HvYfFK/vo9E+H8ssd5qXlsV+QZx9a5H4sXFxb6VYhHK5nHf/ZrW8FzlbjU9v8AfX+VZHxRGZtOz/z1b/0GtMl0qRZrxL/EiDi6FHmuYcVxqAjYG5lDH3PFbGoQsxHJwByKx7fULRPkiIya0hPDOm5jyK+o9jFdD5B0pJtIxGtBMpBBx9Kyr3RjJAUC8fQV1JjjdqfLaQyDDVw1cNzO56WExfIjmrSWe2tzCRzWtYmU2bFuW9frVr7O1tO27nHINdFpenPJaM7LxjiuSphuRXO6ljftDFt9MaaMuDj1FdFbpPFbbeXb0qB9IuNuVQj8K19PtpoRh4yfrWEaHc66mL5kaFhNcx8k4FWZr6fA561eiWNkX5Of8AGs3VbfBXHfvRKi1FkKv7RlC+k9GJPqcVV0W5kiuI/m43CrMsJXLGoNPGXGQea4akbq5pKom7HrFiTJEWFdZpN0bcLzXC6RO9sv7trM7tIOM969epU5KVjxcZg9GzqbfWPMXpVg3vbFcBDrGJQM1syaqRGArGq9ojy3hXcjuh1cK+c0S62v96sK21LfmtFdRV3ww4q4VEYyw0zYl1mJB8jD864q8vJL2+jjJz8wq7eyF3WqhizrKvFb0rPc4sRB30R3ENzc7GGelc3d3cyvjJzWjaN+7/GsC8DJeMc96qrDqjHDy5WcN4kuJlnZCcCsez+1ypjJ+tXvFLBbxwT3rBSaaNfmPIrxMRUfO7H6Hw8o+xi2z03wbcNGdpbnnr+Fexabd7YBn0rwXwtqD+bsBr2ezVjHGMdB+lfnfEOHk5XI/ScpqQjBHyH+2P4W1Lxn8c/CWi6YuZpo2jB9Cx5r5+8S/s7/GW10ya4tdI1SbUbXJJilyqsPQetfqfa+G5Nd+OenXqp5htXluGz6BT/jXz9+234o8H6H8Qv7F0dQbu5fy5Iy2OhPIr5eV1sfbYLHJRSTOB+GX7I/xFH2GVLe4HmpHvMjFisg6/pV74m/s8fFTS7qaOKxuri2HytJC4IYe/vXGal8br7Sx5dnELeMcABc8e1csfijq1y5mN1IhPUB23V0qCOyvjfas+itO/ZH8ceJ9P/tWXSLmaxiGJJVwpGO+0kGm3X7J3jK1BhHh7UizfxFsDNcyvjPxGy4TVr3HXHHN7Hj7ua7lPiH4gkBLX9yen3jzTcYmHt5Hq3wz+Bk/hPwhdadc2P+naiAkbOiuyKB79K5ZfhJqvh28bTdY0m6KRsV+VGGfqCK2/C/x28V+G9NisoJ/O8r7pYZP4mtw/HXxPqe77ZNkj1rm5oopVZno0fge1t4ytzYyqCBiQqcn3xXR6bDb2dvHFGNqxgAV4fL8UXuV23E0jE+prlr7x/rE43rIyfQ0nVjEwrVWz7K0bVBCRvbA9609a13SgsGXG4twB1FfIOi+KtdmvIkF26biAeap+N/HniOSfy01KfyAOF3nitMPWlKfKkceJlHkuz3y9a5kniSJfliXex7YINW7ONrW7t7c9PNQ4+jA14J4b8S63LdQwPcuYnkCsD2zX0mptpJLV5CcmVCfxINfZ0KSnE+Qq/DserWcJJOallt1IJFHl5X86k8sYz6VyVqNuhFJWViiLcbsDvVqO2UN0qpd3P2ZCQOazbfW45mKY5FefKm+g5pGzdWiMc4rJuLbBOBitiKdW5qG4Ve1Yuk4mlOtZnnN1GFc4rKnljiJcnA7111xFFKxbFcbf2LfMxHFXFWPUhNRlca7R6rpk10ZCJMhMHIHHpXxV8cPhnqFvqiavYI0igk5A4619vXJUGGINl3YKP8AvE4r5R/aMt20/V7e0c8bsH8Ka0M6ztE8S8M6zHPdrp0x+Yt0Ne5aFGIxb+VwIwB+deY/C3wS2u66rLGS4PLD0r2HVrZtNi8sJsZOCDXNUkbJ2Oshu5YkJViozyKzZ9RuGXBYkd6pR38c5WAdRUzSQW6Fmb5ql7mYW7kgKSnJr0XQIT5CuD8w5FcHBeWQn4Y5Nb9vq6W8IjK56VhJajRp+JPFUWiWD3WDvxkCvFdW1bX/ELxTOGS1Rl2BjmtrxVdtclxjPPSsa2n2RrH0xQh3PTvh9o6Wlqsq43kZr6J8P3H2e2JHDHoPpXlvguFF09XA5xxXpVmiRxJIP4jk/nWkloM4H4v6fa6rorS3EavLGrEA/SvHbLUHOnRbOPl4r3PxxYxvpsrL824dfxrxtrZFsQSMdKEr7hJHb+F7p5oIuoA6V9j+BpDLbKcZ+UV8NeH7nZI0XYVQ+Km1J/FfxAt/DaymPTZJVdlHchepFfKYqShV5+h+kZFR9phY+Z7F+1/8N7a78E67rNjCq3UMJa5AHJHrX5c/Df4n6roFh9ikBZQePwFfvdqvhax8T+AbrSr5A8NzbbHB9Bjivg+X9j7wbLqJkSwVsEkfN3zXo0sXD4ZbnFLCzV2lZn0Z4Y1UXWiWlzn74B/SuqXqPcVi+D9CfwrpUWniESiAAIT6CupV0fkCtKitFMqitS2GBGRXifxC1SSKK4sUb5Yl3EnoK9iN1FGCGarJ8P2MNubmWMF1GST1zXHUjZ8p1w0PjtdX1Oa/C6bCDEw+bPB/OtDVvDNzceVPpZLFTnA4P5V7j/wjNjO7yW0OHznIFLNoxtMJPKEX4VtB7s1qRPl74j/A668cafHqsyC2nVctGOCCOhFfNesfso/FHSJXktFa5j6gJyK/WV7CKWBpMqxxyarGytZICnXPes/bVadTlRzuFOfvHxZ8BP2TXsL6G9162eNUIYKy4z7V9y+N9CeLwVcCJcGOLOBxxXR3GjxBT5KlPpXIeNHez8K3bHt8v5g11RxbvZvQ0VGKVz8NfhZDFZeO9U1rWWc/aJpHkOcAlnJ/qa+g9L1z7OFl3ZVq+cvA+5/G3jKFOkGo3CgemHNer3F/PaQ7EfArz5O7Pq8LorBr97JKw3VymqXSNKEHFc0bm5FwBu9a9HVUmiQkdqwPDPhF9Y1K9lYfJEML+Arm5tGaVUkrm9olvsuE9+K9TtbpUjjz1AFeNW0l1psx8kna1dR/wkSJGFnflT0r6fK5ODPk8yjKa3PYItQthHkgcVg6u7XO0IuA3f0ri7PxBDc/u1PIrpo7oMgI7V72Gqp6Hztelyp3NWzsJVUgcYrctbclRmuNsfEFvFcfvGOPYV2FprOn7MeSc17sKyW58zXoS5tTprSwkCkf1rVjspFXBrIivLd8bePpW8l9bxqMHFE5O2hzezaHtasv0rG1LT/tI+WmX2u20X3Z8H61GupwT525JrjlN9We1hKMIq5w+t+FWkLMx/WvPr/wq6uXjBr2a8ihuYS3T8q5a6sS3T5RXHWxEou59Dl7i3seTDTpk6jIqjNbzKeQa9OaxkljYCPGa5q70ydeeuKVHGyk9T6fMsLGlFNFLT7uWMfuyc+ua9Z8L3P2q1aGdgyA5GcViabphZEU9Bzn2rptN0h4Hzg9K9CMlJEYWpaXue2eFwqIFHUAZr6E8K65bw6YscpAYD0r5N8P3n2V1bH6E10l54ot0jMcExkCnH0r6fCSlGj73wnyvE9VQqpvdHofjJjf6ZiAE7ueO9eMJazWrfvCenNdZB4jMEPnPJy3asuTVYrubBHPWuWtf4mfF0sZfY2dPmt2kRZHwetd0uqRQ2W0jdXmq/aJJAqD5K1E+0xYDE8968WtWvotj6Shiubd7GjdamBNhOPpW9pkfnsGIxiuKjglLAt3rpNOeXaFU4rqoSUjzMVFuXudzo9s0sucdK6G0Vg2VrJ0iBrdFfORXU2o6f56+4xX0Vro+HqSe7PI/iHZ+dBKTxxXzxE8sMvpkc196a14bKsz4654r5P8Q6OXkfyvw/OvQwvuqzEzZ8CTPJeiJgSSOldtqVgBESFryuzjl067XHpXfR6qHtfJc5yMV6kVpqc6kfN/wAUb1dG1p7cna2a5ex1GK7+9jNev/ELwfBr97vUHzGP6V47F4Vu7BmYKxQH1r18LV5o2OipG5NN4lGlxMg4H9a9H+G3ixbu4WJeASK8guNL+0uyMvFdB4PjWwvxGnDg8V2bOxyy3PTvH2mia1e9RfnjHOO4rnNM8S3l7bi2ZuAAMivUbC3j1nR3tph8zjYT6g+9ef6B4buE1y4t0H+jqwII9KTJSaO68M3j/aFUmpdQ1i3guGRjWNoErxagVX1xVvxJp15BMsqg/NWMlclx1O+8O60YoVbNWNS1bflFIrzrQ7y8B2nPHvXYQXJlA3DmslIuKVzfh1iVflapo7+SYbT0NY0MZZRV77Kbf5g3PpWLZ0SRs2r7TuzXSWLhR3rmYJM1tQn5R9KUtjKSO5s2W5TDdDXUaVH5WUBPNN8MaeFgVuhIIrcu4o7O0mnJ+7GxA9SBxXnyegHkPi261GxvUe2dn3MMkntXcWl3M2m2kzqVeRRnPuKwPFVm11DIZ+WVsjnpW3p6k6ZbsMYK96pkrVHl/xE1i+tjpixBzh7hcKO56V6n8LI2nvLaSXhlgJIPbcKo+LfC0Wr6ZHPbY3LJJkDuCcGus+FmkDTr7a/DNGo/JxQkCZ7Mib3CAZJOBivkD9obwl4rXyYtMsPMsTdCaZ88qhK5x19K+tLQiIlmr5z/an+KcPgjwNdJYhft10Sx3DKpIB0+nNcrxKp4mMJOyZ2YGMKlSKlsfBHiHTZJtS1iRVyrTblI9GOWH4YNbmiWiNHhhjNcP4m8Zyz3s92FCtcv5hx1O4k16H4bk0tbaMGUCR+R71jisUqMb9T6bBYVVJqNhf7Ji+7/OoNS8LJNbMiHBPuRVu3voowAfzrbttSt/Lauo8yr5Ttl0AXNoARjIrV0DwikdsrdMU3VNQhgsiIiMjFWdF1GOKDYzcGuKrWutT3fqkra/8A1Ox8Nxx21wCBggdQR7V3cFo0TROeBvC/meB/Pj8K8wsb/f5ajGBWpd3xkZQhO1T94HrkdOa5qVaTkTLCJJy0PYsEcEYNNgJlmCKMluAPU1gaZqMaW0bSS5kC5wMnJ9K0LO8LSl4yRxjPXB9K1qS91mMqXLqdFbCO2Kxt3Jxmnm5beTt4HXisj7RAi5LhWH8JrPk1WGOM7XBJ7jFZKVzPk1F1K+EQ+bpXHX82B05Ncvq/iKO0fbkZz3rmX8Q293IdrFT6VLqNHbGjJLU9Csb8iBY+c9q1Y79I4irnrXHaXrbhNqt26CtMXzXHBb06VjKd9z0sPS5Vdl07XVs9jVm4hEnLDmo7FXdwCOPatiGzeSPk9BUnWpM4u7VGQ7cVSS2XkAcV6LaabFJAd+CTWPLp8VvcEY/CsZ1VE2pUOZGdAlymDEcH0rV03W3tdUiZ48q8ioScEkZPf869h+BfhDwhr/iF7TxXp7TRuqmFwxHlsHGeoOa+8NV/Ys/ZP1oLNNp76LdxsGS4sJioB/wB0NsP/AHzVUnWrRbhHb8TjrxhSdnufM/wg+GNz4g1V7h7OSR3GRtGcD3FZev2msaL4r1bS7eMm0jlbaxH45r9JfDXw68E+CdBisvC3h+00iCbAcQQhHcDpukGHb8WNcJ8SPDvg/XXXQjO0d5bt5jqpJBIxjFYPIKM6nPFKPZLbuRzXPFdG8Wx6VArxnauMAY61o3PiqCynCTKQT0AHNde6JYotzYHzBBtCHkY9PyrP1/QL29Sz1COJHe4X98I1Cs2ByWXvx1r1cHS9m3F7HmYuqq9BzWjFi1q0uIlgSXa7dB6+vNaVu6pHjbyx4rJi0mOYnA4x09K1re2RFAHauypJW1PJiuZlXULhG+UDoa5e7u0hJC9a6nUVVIyK5CaAszsfWvPqWex7GCirXQv2TqoJxk16D4K1GDDwyADnPNeRLLIMKjFQK6rw5evoN8L0AlcYIx3NddCMrHj47DqaZ9haXdIY1IP0rZ3Lj1rz/wd4isr+ENBO0jgDJxiuvlu1UVrJ3enwvOyP/9k='

# ── EMBEDDED SOUND (Base64 WAV) ───────────────────────────────
$SOUND_B64 = 'UklGRmQfAABXQVZFZm10IBAAAAABAAEAQB8AAEAfAAABAAgAZGF0YUAfAACAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgA=='

# ==============================================================
#  Everything below this line runs automatically
# ==============================================================

Add-Type -AssemblyName System.Windows.Forms
Add-Type -AssemblyName System.Drawing

# ── Win32: ClipCursor ─────────────────────────────────────────
Add-Type @"
using System;
using System.Runtime.InteropServices;
public class Win32Cursor {
    [DllImport("user32.dll")]
    public static extern bool ClipCursor(ref RECT r);
    [DllImport("user32.dll")]
    public static extern bool ClipCursor(IntPtr r);
    [StructLayout(LayoutKind.Sequential)]
    public struct RECT { public int Left, Top, Right, Bottom; }
}
"@

# ── COM Audio API: set master volume ──────────────────────────
Add-Type @"
using System.Runtime.InteropServices;
[Guid("5CDF2C82-841E-4546-9722-0CF74078229A"),InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]
interface IAudioEndpointVolume {
    int _1();int _2();int _3();int _4();
    int SetMasterVolumeLevelScalar(float f, System.Guid g);
    int _6();
    int GetMasterVolumeLevelScalar(out float f);
    int SetMute([MarshalAs(UnmanagedType.Bool)]bool b, System.Guid g);
    int GetMute(out bool b);
}
[Guid("D666063F-1587-4E43-81F1-B948E807363F"),InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]
interface IMMDevice {
    int Activate(ref System.Guid id,int ctx,int p,[MarshalAs(UnmanagedType.IUnknown)]out object o);
}
[Guid("A95664D2-9614-4F35-A746-DE8DB63617E6"),InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]
interface IMMDeviceEnumerator {
    int _1();
    int GetDefaultAudioEndpoint(int flow,int role,out IMMDevice d);
}
[ComImport,Guid("BCDE0395-E52F-467C-8E3D-C4579291692E")]
class MMDeviceEnumeratorComObject {}
public class VolumeHelper {
    public static void SetMax() {
        var e=(IMMDeviceEnumerator)new MMDeviceEnumeratorComObject();
        IMMDevice d; e.GetDefaultAudioEndpoint(0,1,out d);
        var iid=new System.Guid("5CDF2C82-841E-4546-9722-0CF74078229A");
        object v; d.Activate(ref iid,23,0,out v);
        var ep=(IAudioEndpointVolume)v;
        ep.SetMasterVolumeLevelScalar(1.0f,System.Guid.Empty);
        ep.SetMute(false,System.Guid.Empty);
    }
}
"@

# ── 1. Decode embedded files to TEMP ──────────────────────────
$tmpImg   = [IO.Path]::Combine([IO.Path]::GetTempPath(), "alert_img.$ImageExt")
$tmpSound = [IO.Path]::Combine([IO.Path]::GetTempPath(), "alert_snd.$SoundExt")

[IO.File]::WriteAllBytes($tmpImg,   [Convert]::FromBase64String($IMAGE_B64))
[IO.File]::WriteAllBytes($tmpSound, [Convert]::FromBase64String($SOUND_B64))

# ── 2. Wait ────────────────────────────────────────────────────
Start-Sleep -Seconds $DelaySeconds

# ── 3. Volume to 100% ─────────────────────────────────────────
try { [VolumeHelper]::SetMax() } catch { Write-Warning "Volume failed: $_" }

# ── 4. Build fullscreen form ───────────────────────────────────
$form = New-Object System.Windows.Forms.Form
$form.Text            = ""
$form.FormBorderStyle = [System.Windows.Forms.FormBorderStyle]::None
$form.WindowState     = [System.Windows.Forms.FormWindowState]::Maximized
$form.TopMost         = $true
$form.BackColor       = [System.Drawing.Color]::Black
$form.Cursor          = [System.Windows.Forms.Cursors]::None

$pb           = New-Object System.Windows.Forms.PictureBox
$pb.Dock      = [System.Windows.Forms.DockStyle]::Fill
$pb.SizeMode  = [System.Windows.Forms.PictureBoxSizeMode]::StretchImage
$pb.Image     = [System.Drawing.Image]::FromFile($tmpImg)
$form.Controls.Add($pb)

# ── 5. Play sound looping ─────────────────────────────────────
$player = New-Object System.Media.SoundPlayer($tmpSound)
$player.PlayLooping()

# ── 6. Lock mouse to primary screen ───────────────────────────
$bounds = [System.Windows.Forms.Screen]::PrimaryScreen.Bounds
$rect   = New-Object Win32Cursor+RECT
$rect.Left=$bounds.Left; $rect.Top=$bounds.Top
$rect.Right=$bounds.Right; $rect.Bottom=$bounds.Bottom
[Win32Cursor]::ClipCursor([ref]$rect) | Out-Null

# ── 7. Block keyboard & prevent manual close ─────────────────
$script:allowClose = $false

$form.KeyPreview = $true
$form.Add_KeyDown({
    $_.SuppressKeyPress = $true
    $_.Handled = $true
})

$form.Add_FormClosing({
    if (-not $script:allowClose) {
        $_.Cancel = $true
    }
})

# ── 8. Auto-close timer (10 seconds) ─────────────────────────
$timer          = New-Object System.Windows.Forms.Timer
$timer.Interval = 10 * 1000
$timer.Add_Tick({
    $timer.Stop()
    $script:allowClose = $true
    $form.Close()
})
$timer.Start()

# ── 9. Run (blocks here until timer fires) ────────────────────
[System.Windows.Forms.Application]::Run($form)

# ── 10. Cleanup ───────────────────────────────────────────────
$player.Stop()
[Win32Cursor]::ClipCursor([System.IntPtr]::Zero) | Out-Null
$pb.Image.Dispose()
Remove-Item $tmpImg   -Force -ErrorAction SilentlyContinue
Remove-Item $tmpSound -Force -ErrorAction SilentlyContinue
